import XCTest
@testable import FluxTraining

final class LocalizedCopyTests: XCTestCase {
  func test_spanishIsBaseLanguage() {
    let copy = LocalizedCopy(language: .es)

    XCTAssertEqual(copy.text(.heroTitle), "Entrena con foco y seguimiento real")
    XCTAssertEqual(copy.text(.trainingTitle), "Entrenamiento")
    XCTAssertEqual(copy.text(.operationsNavigationTitle), "Ajustes")
    XCTAssertEqual(copy.text(.domainFilterLabel), "Dominio")
    XCTAssertEqual(copy.text(.domainOperations), "Operaciones")
    XCTAssertEqual(copy.text(.offlineSyncTitle), "Offline + Sync")
    XCTAssertEqual(copy.text(.trackEvent), "Registrar evento")
    XCTAssertEqual(copy.text(.emailField), "Correo")
    XCTAssertEqual(copy.text(.passwordField), "Contrasena")
    XCTAssertEqual(copy.text(.recoverByEmail), "Recuperar por email")
    XCTAssertEqual(copy.text(.recoverBySMS), "Recuperar por SMS")
    XCTAssertEqual(copy.text(.authenticationTitle), "Acceso")
    XCTAssertEqual(copy.text(.readinessLabel), "Preparacion")
    XCTAssertEqual(copy.text(.applePermissionHealthKitRead), "Lectura de HealthKit")
    XCTAssertEqual(copy.text(.applePermissionCalendarEvents), "Eventos del calendario")
    XCTAssertEqual(copy.text(.rememberMe), "recordarme")
    XCTAssertEqual(copy.text(.forgotPassword), "olvide mi contrasena")
    XCTAssertEqual(copy.text(.languageOptionSpanish), "ES")
    XCTAssertEqual(copy.text(.languageOptionEnglish), "EN")
    XCTAssertEqual(copy.text(.runtimeStateSectionTitle), "Estado enterprise por dominio")
    XCTAssertEqual(copy.text(.runtimeStateModeLabel), "Modo runtime")
    XCTAssertEqual(copy.text(.runtimeStateRecoveryAction), "Recuperar dominio")
    XCTAssertEqual(copy.text(.idempotencyKeyLabel), "Clave idempotencia")
    XCTAssertEqual(copy.text(.idempotencyReplayLabel), "Replay idempotente")
    XCTAssertEqual(copy.text(.idempotencyReplayYes), "si")
    XCTAssertEqual(copy.text(.idempotencyReplayNo), "no")
    XCTAssertEqual(copy.text(.idempotencyTTLLabel), "TTL idempotencia")
    XCTAssertEqual(copy.text(.supportIncidentsLabel), "Incidencias de soporte")
    XCTAssertEqual(copy.text(.incidentCorrelationLabel), "Correlacion")
    XCTAssertEqual(copy.text(.roleLabel), "Rol")
    XCTAssertEqual(copy.text(.roleAthlete), "Atleta")
    XCTAssertEqual(copy.text(.roleCoach), "Coach")
    XCTAssertEqual(copy.text(.roleAdmin), "Admin")
    XCTAssertEqual(copy.text(.settingsTitle), "Ajustes")
    XCTAssertEqual(copy.text(.legalSectionTitle), "Privacidad y consentimiento")
    XCTAssertEqual(copy.text(.acceptPrivacyPolicy), "Acepto politica de privacidad")
    XCTAssertEqual(copy.text(.trainingCockpitTitle), "Cockpit diario")
    XCTAssertEqual(copy.text(.videoPlayerTitle), "Reproductor de video")
    XCTAssertEqual(copy.text(.playSelectedVideoAction), "Reproducir video")
    XCTAssertEqual(copy.text(.progressTitle), "Resumen de progreso")
    XCTAssertEqual(copy.text(.loadProgress), "Cargar progreso")
    XCTAssertEqual(copy.text(.noProgressLoaded), "Todavia no hay progreso cargado")
    XCTAssertEqual(copy.text(.videoFallbackNotice), "Mostrando fallback EN por falta de video en idioma solicitado.")
    XCTAssertEqual(copy.humanStatus("signed_out"), "inicia sesion")
    XCTAssertEqual(copy.humanStatus("validation_error"), "error de validacion")
    XCTAssertEqual(copy.humanStatus("consent_required"), "consentimiento requerido")
    XCTAssertEqual(copy.humanStatus("recovery_sent_email"), "recuperacion enviada por email")
    XCTAssertEqual(copy.humanStatus("recovery_sent_sms"), "recuperacion enviada por sms")
    XCTAssertEqual(copy.humanStatus("session_active"), "sesion activa")
    XCTAssertEqual(copy.humanStatus("fallback_loaded"), "fallback cargado")
    XCTAssertEqual(copy.humanStatus("exported"), "exportado")
    XCTAssertEqual(copy.humanStatus("loading"), "cargando")
    XCTAssertEqual(copy.humanStatus("empty"), "sin datos")
    XCTAssertEqual(copy.humanStatus("offline"), "sin conexion")
    XCTAssertEqual(copy.humanStatus("denied"), "sin permiso")
    XCTAssertEqual(copy.humanStatus("open"), "en revision")
    XCTAssertEqual(copy.humanStatus("in_progress"), "en progreso")
    XCTAssertEqual(copy.humanStatus("resolved"), "resuelta")
    XCTAssertNil(copy.authFeedback("signed_out"))
    XCTAssertEqual(copy.authFeedback("auth_error"), "No pudimos iniciar sesion. Intentalo otra vez.")
    XCTAssertEqual(copy.authFeedback("open"), "Soporte informado. Revisaremos tu caso.")
    XCTAssertEqual(copy.authFeedback("signed_in:apple"), "Sesion iniciada correctamente.")
  }

  func test_englishTranslationsAreAvailable() {
    let copy = LocalizedCopy(language: .en)

    XCTAssertEqual(copy.text(.heroTitle), "Train with focus and real tracking")
    XCTAssertEqual(copy.text(.trainingTitle), "Training")
    XCTAssertEqual(copy.text(.domainFilterLabel), "Domain")
    XCTAssertEqual(copy.text(.domainOperations), "Operations")
    XCTAssertEqual(copy.text(.offlineSyncTitle), "Offline + Sync")
    XCTAssertEqual(copy.text(.trackEvent), "Track event")
    XCTAssertEqual(copy.text(.emailField), "Email")
    XCTAssertEqual(copy.text(.passwordField), "Password")
    XCTAssertEqual(copy.text(.recoverByEmail), "Recover by email")
    XCTAssertEqual(copy.text(.recoverBySMS), "Recover by SMS")
    XCTAssertEqual(copy.text(.rememberMe), "remember me")
    XCTAssertEqual(copy.text(.forgotPassword), "forgot password?")
    XCTAssertEqual(copy.text(.languageOptionSpanish), "ES")
    XCTAssertEqual(copy.text(.languageOptionEnglish), "EN")
    XCTAssertEqual(copy.text(.runtimeStateSectionTitle), "Enterprise runtime state by domain")
    XCTAssertEqual(copy.text(.runtimeStateModeLabel), "Runtime mode")
    XCTAssertEqual(copy.text(.runtimeStateRecoveryAction), "Recover domain")
    XCTAssertEqual(copy.text(.idempotencyKeyLabel), "Idempotency key")
    XCTAssertEqual(copy.text(.idempotencyReplayLabel), "Idempotency replay")
    XCTAssertEqual(copy.text(.idempotencyReplayYes), "yes")
    XCTAssertEqual(copy.text(.idempotencyReplayNo), "no")
    XCTAssertEqual(copy.text(.idempotencyTTLLabel), "Idempotency TTL")
    XCTAssertEqual(copy.text(.supportIncidentsLabel), "Support incidents")
    XCTAssertEqual(copy.text(.incidentCorrelationLabel), "Correlation")
    XCTAssertEqual(copy.text(.roleLabel), "Role")
    XCTAssertEqual(copy.text(.roleAthlete), "Athlete")
    XCTAssertEqual(copy.text(.roleCoach), "Coach")
    XCTAssertEqual(copy.text(.roleAdmin), "Admin")
    XCTAssertEqual(copy.text(.settingsTitle), "Settings")
    XCTAssertEqual(copy.text(.legalSectionTitle), "Privacy and consent")
    XCTAssertEqual(copy.text(.acceptPrivacyPolicy), "I accept the privacy policy")
    XCTAssertEqual(copy.text(.trainingCockpitTitle), "Daily cockpit")
    XCTAssertEqual(copy.text(.videoPlayerTitle), "Video player")
    XCTAssertEqual(copy.text(.playSelectedVideoAction), "Play video")
    XCTAssertEqual(copy.text(.progressTitle), "Progress summary")
    XCTAssertEqual(copy.text(.loadProgress), "Load progress")
    XCTAssertEqual(copy.text(.noProgressLoaded), "No progress loaded yet")
    XCTAssertEqual(copy.text(.videoFallbackNotice), "Showing EN fallback because requested locale has no video.")
    XCTAssertEqual(copy.humanStatus("signed_out"), "sign in to continue")
    XCTAssertEqual(copy.humanStatus("validation_error"), "validation error")
    XCTAssertEqual(copy.humanStatus("consent_required"), "consent required")
    XCTAssertEqual(copy.humanStatus("recovery_sent_email"), "recovery sent by email")
    XCTAssertEqual(copy.humanStatus("recovery_sent_sms"), "recovery sent by sms")
    XCTAssertEqual(copy.humanStatus("session_active"), "session active")
    XCTAssertEqual(copy.humanStatus("fallback_loaded"), "fallback loaded")
    XCTAssertEqual(copy.humanStatus("exported"), "exported")
    XCTAssertEqual(copy.humanStatus("loading"), "loading")
    XCTAssertEqual(copy.humanStatus("empty"), "empty")
    XCTAssertEqual(copy.humanStatus("offline"), "offline")
    XCTAssertEqual(copy.humanStatus("denied"), "denied")
    XCTAssertEqual(copy.humanStatus("open"), "under review")
    XCTAssertEqual(copy.humanStatus("in_progress"), "in progress")
    XCTAssertEqual(copy.humanStatus("resolved"), "resolved")
    XCTAssertNil(copy.authFeedback("signed_out"))
    XCTAssertEqual(copy.authFeedback("auth_error"), "We couldn't sign you in. Please try again.")
    XCTAssertEqual(copy.authFeedback("open"), "Support was notified. We'll review your case.")
    XCTAssertEqual(copy.authFeedback("signed_in:apple"), "Signed in successfully.")
  }
}
