import XCTest
@testable import FluxTraining

final class LocalizedCopyTests: XCTestCase {
  func test_spanishIsBaseLanguage() {
    let copy = LocalizedCopy(language: .es)

    XCTAssertEqual(copy.text(.heroTitle), "Entrena con foco y seguimiento real")
    XCTAssertEqual(copy.text(.trainingTitle), "Entrenamiento")
    XCTAssertEqual(copy.text(.domainFilterLabel), "Dominio")
    XCTAssertEqual(copy.text(.domainOperations), "Operaciones")
    XCTAssertEqual(copy.text(.offlineSyncTitle), "Offline + Sync")
    XCTAssertEqual(copy.text(.trackEvent), "Registrar evento")
    XCTAssertEqual(copy.text(.emailField), "Correo")
    XCTAssertEqual(copy.text(.passwordField), "Contrasena")
    XCTAssertEqual(copy.text(.recoverByEmail), "Recuperar por email")
    XCTAssertEqual(copy.text(.recoverBySMS), "Recuperar por SMS")
    XCTAssertEqual(copy.text(.languageOptionSpanish), "ES")
    XCTAssertEqual(copy.text(.languageOptionEnglish), "EN")
    XCTAssertEqual(copy.text(.runtimeStateSectionTitle), "Estado enterprise por dominio")
    XCTAssertEqual(copy.text(.runtimeStateModeLabel), "Modo runtime")
    XCTAssertEqual(copy.text(.runtimeStateRecoveryAction), "Recuperar dominio")
    XCTAssertEqual(copy.text(.roleLabel), "Rol")
    XCTAssertEqual(copy.text(.roleAthlete), "Atleta")
    XCTAssertEqual(copy.text(.roleCoach), "Coach")
    XCTAssertEqual(copy.text(.roleAdmin), "Admin")
    XCTAssertEqual(copy.text(.settingsTitle), "Ajustes")
    XCTAssertEqual(copy.text(.legalSectionTitle), "Privacidad y consentimiento")
    XCTAssertEqual(copy.text(.acceptPrivacyPolicy), "Acepto politica de privacidad")
    XCTAssertEqual(copy.humanStatus("signed_out"), "sin sesion")
    XCTAssertEqual(copy.humanStatus("validation_error"), "error de validacion")
    XCTAssertEqual(copy.humanStatus("consent_required"), "consentimiento requerido")
    XCTAssertEqual(copy.humanStatus("recovery_sent_email"), "recuperacion enviada por email")
    XCTAssertEqual(copy.humanStatus("recovery_sent_sms"), "recuperacion enviada por sms")
    XCTAssertEqual(copy.humanStatus("exported"), "exportado")
    XCTAssertEqual(copy.humanStatus("loading"), "cargando")
    XCTAssertEqual(copy.humanStatus("offline"), "sin conexion")
    XCTAssertEqual(copy.humanStatus("denied"), "sin permiso")
  }

  func test_englishTranslationsAreAvailable() {
    let copy = LocalizedCopy(language: .en)

    XCTAssertEqual(copy.text(.heroTitle), "Train with focus and real tracking")
    XCTAssertEqual(copy.text(.trainingTitle), "Training")
    XCTAssertEqual(copy.text(.domainFilterLabel), "Domain")
    XCTAssertEqual(copy.text(.domainOperations), "Operations")
    XCTAssertEqual(copy.text(.offlineSyncTitle), "Offline + Sync")
    XCTAssertEqual(copy.text(.trackEvent), "Track event")
    XCTAssertEqual(copy.text(.emailField), "Email")
    XCTAssertEqual(copy.text(.passwordField), "Password")
    XCTAssertEqual(copy.text(.recoverByEmail), "Recover by email")
    XCTAssertEqual(copy.text(.recoverBySMS), "Recover by SMS")
    XCTAssertEqual(copy.text(.languageOptionSpanish), "ES")
    XCTAssertEqual(copy.text(.languageOptionEnglish), "EN")
    XCTAssertEqual(copy.text(.runtimeStateSectionTitle), "Enterprise runtime state by domain")
    XCTAssertEqual(copy.text(.runtimeStateModeLabel), "Runtime mode")
    XCTAssertEqual(copy.text(.runtimeStateRecoveryAction), "Recover domain")
    XCTAssertEqual(copy.text(.roleLabel), "Role")
    XCTAssertEqual(copy.text(.roleAthlete), "Athlete")
    XCTAssertEqual(copy.text(.roleCoach), "Coach")
    XCTAssertEqual(copy.text(.roleAdmin), "Admin")
    XCTAssertEqual(copy.text(.settingsTitle), "Settings")
    XCTAssertEqual(copy.text(.legalSectionTitle), "Privacy and consent")
    XCTAssertEqual(copy.text(.acceptPrivacyPolicy), "I accept the privacy policy")
    XCTAssertEqual(copy.humanStatus("signed_out"), "signed out")
    XCTAssertEqual(copy.humanStatus("validation_error"), "validation error")
    XCTAssertEqual(copy.humanStatus("consent_required"), "consent required")
    XCTAssertEqual(copy.humanStatus("recovery_sent_email"), "recovery sent by email")
    XCTAssertEqual(copy.humanStatus("recovery_sent_sms"), "recovery sent by sms")
    XCTAssertEqual(copy.humanStatus("exported"), "exported")
    XCTAssertEqual(copy.humanStatus("loading"), "loading")
    XCTAssertEqual(copy.humanStatus("offline"), "offline")
    XCTAssertEqual(copy.humanStatus("denied"), "denied")
  }
}
